import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface GeneratePostRequest {
  textInput?: string;
  imageUrl?: string;
  platform?: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    // Get the authorization header
    const authHeader = req.headers.get("Authorization")!;
    
    // Create Supabase client
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      { global: { headers: { Authorization: authHeader } } }
    );

    // Get the current user
    const {
      data: { user },
    } = await supabaseClient.auth.getUser();

    if (!user) {
      throw new Error("Unauthorized");
    }

    // Parse request body
    const { textInput, imageUrl, platform = "linkedin" }: GeneratePostRequest = await req.json();

    // TODO: Integrate with your preferred AI service (OpenAI, Anthropic, etc.)
    // For now, return mock generated content
    
    const mockPost = `🚀 ${textInput ? textInput : "Exciting update from the field!"}

This is a placeholder generated by the AI Post Generator. In production, this will be replaced with actual AI-generated content tailored to your input.

What's your take on this? Let me know in the comments! 👇

#Innovation #Growth #Leadership`;

    // Store the upload
    const { data: upload, error: uploadError } = await supabaseClient
      .from("uploads")
      .insert({
        user_id: user.id,
        type: imageUrl ? "image" : "text",
        image_url: imageUrl,
        text: textInput,
        status: "completed",
      })
      .select()
      .single();

    if (uploadError) {
      console.error("Upload error:", uploadError);
    }

    // Store the generated post
    const { data: generatedPost, error: postError } = await supabaseClient
      .from("generated_posts")
      .insert({
        user_id: user.id,
        upload_id: upload?.id,
        content: mockPost,
        platform,
        status: "draft",
      })
      .select()
      .single();

    if (postError) {
      console.error("Post error:", postError);
    }

    return new Response(
      JSON.stringify({
        success: true,
        post: mockPost,
        postId: generatedPost?.id,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 400,
      }
    );
  }
});

