import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import {
  BASE_CORS_HEADERS as corsHeaders,
  errorMessage,
  errorResponse,
  jsonResponse,
  preflightResponse,
} from "../_shared/http.ts";
import { callerClient, getCallerUser } from "../_shared/supabase.ts";

interface GeneratePostRequest {
  textInput?: string;
  imageUrl?: string;
  platform?: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return preflightResponse(corsHeaders);
  }

  try {
    const supabaseClient = callerClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      req.headers.get("Authorization"),
    );

    const user = await getCallerUser(supabaseClient);

    if (!user) {
      throw new Error("Unauthorized");
    }

    // Parse request body
    const { textInput, imageUrl, platform = "linkedin" }: GeneratePostRequest = await req.json();

    // TODO: Integrate with your preferred AI service (OpenAI, Anthropic, etc.)
    // For now, return mock generated content
    
    const mockPost = `🚀 ${textInput ? textInput : "Exciting update from the field!"}

This is a placeholder generated by the AI Post Generator. In production, this will be replaced with actual AI-generated content tailored to your input.

What's your take on this? Let me know in the comments! 👇

#Innovation #Growth #Leadership`;

    // Store the upload
    const { data: upload, error: uploadError } = await supabaseClient
      .from("uploads")
      .insert({
        user_id: user.id,
        type: imageUrl ? "image" : "text",
        image_url: imageUrl,
        text: textInput,
        status: "completed",
      })
      .select()
      .single();

    if (uploadError) {
      console.error("Upload error:", uploadError);
    }

    // Store the generated post
    const { data: generatedPost, error: postError } = await supabaseClient
      .from("generated_posts")
      .insert({
        user_id: user.id,
        upload_id: upload?.id,
        content: mockPost,
        platform,
        status: "draft",
      })
      .select()
      .single();

    if (postError) {
      console.error("Post error:", postError);
    }

    return jsonResponse(
      { success: true, post: mockPost, postId: generatedPost?.id },
      200,
      corsHeaders,
    );
  } catch (error) {
    return errorResponse(errorMessage(error), 400, corsHeaders);
  }
});

